blueprint:
  name: Zigbee2MQTT 2.0 - Tuya 4-Button Scene Switch
  description: Automate your Tuya 4-Button Scene Switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: Tuya 4-Button Scene Switch
      description: Select the Tuya 4-Button Scene Switch to use
      selector:
        device:
          integration: mqtt
    fan_target:
      name: Fan
      selector:
        target:
          entity:
            domain: fan

trigger:
  # Button 1 Triggers
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 1_single
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 1_double
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 1_hold

  # Button 2 Triggers
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 2_single
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 2_double
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 2_hold

  # Button 3 Triggers
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 3_single
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 3_double
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 3_hold

  # Button 4 Triggers
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 4_single
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 4_double
  - platform: device
    device_id: !input switch
    domain: mqtt
    type: action
    subtype: 4_hold

action:
  - variables:
      command: '{{ trigger.payload }}'
  - choose:
    - conditions:
      - '{{ command == ''1_single'' }}'
      sequence: !input button_one_short_press
    - conditions:
      - '{{ command == ''2_single'' }}'
      sequence: !input button_two_short_press
    - conditions:
      - '{{ command == ''3_single'' }}'
      sequence: !input button_three_short_press
    - conditions:
      - '{{ command == ''4_single'' }}'
      sequence: !input button_four_short_press
    - conditions:
      - '{{ command == ''1_double'' }}'
      sequence: !input button_one_double_press
    - conditions:
      - '{{ command == ''2_double'' }}'
      sequence: !input button_two_double_press
    - conditions:
      - '{{ command == ''3_double'' }}'
      sequence: !input button_three_double_press
    - conditions:
      - '{{ command == ''4_double'' }}'
      sequence: !input button_four_double_press
    - conditions:
      - '{{ command == ''1_hold'' }}'
      sequence: !input button_one_long_press
    - conditions:
      - '{{ command == ''2_hold'' }}'
      sequence: !input button_two_long_press
    - conditions:
      - '{{ command == ''3_hold'' }}'
      sequence: !input button_three_long_press
    - conditions:
      - '{{ command == ''4_hold'' }}'
      sequence: !input button_four_long_press

mode: single
max_exceeded: silent
